apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: nginx
spec:
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx
                  ports:
                      - containerPort: 80

                  volumeMounts:
                      - mountPath: /etc/nginx/conf.d
                        readOnly: true
                        name: nginx-conf
