apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: app

spec:
    selector:
        matchLabels:
            app: app

    template:
        metadata:
            labels:
                app: app
        spec:
            containers:
                - name: app
                    image: img-app-deployment
                    ports:
                    - containerPort: 80

                    envFrom:
                    - configMapRef:
                        name: app-conf

            volumes:
                - name: app-conf
                  configMap:
                    name: app-conf
